Repository CSE-25/amrita_pyq, pull requests merged in 2025-01, with the labels that each got.

#20 Improve Code Quality and Comment Clarity
  cmd/configs.go
  cmd/helpers.go
  cmd/logo.go
  cmd/model.go
  cmd/requestClient.go
  cmd/root.go
  cmd/semChoose.go
  cmd/semTable.go
  cmd/stack.go
  cmd/version.go
  cmd/year.go
Labels: AMWOC, AMWOC-accepted, BOUNTY-30

#23 Added vitepress docs website
  .github/workflows/deploy.yaml
  .gitignore
  docs/.prettierignore
  docs/.prettierrc
  docs/.vitepress/config.js
  docs/getting-started.md
  docs/index.md
  docs/package-lock.json
  docs/package.json
Labels: documentation, AMWOC, AMWOC-accepted

#21 [COMPLETED] Add Charmbracelet Huh List to Select Courses.
  README.md
  cmd/helpers.go
  cmd/root.go
  cmd/semChoose.go
  cmd/semTable.go
  cmd/year.go
  docs/CODE_OF_CONDUCT.md
  docs/SECURITY.md
  go.mod
  go.sum
  main.go
Labels: AMWOC, AMWOC-accepted
