Repository CSE-25/amrita_pyq, pull requests merged in 2025-02, with the labels that each got.

#27 Add @FLASH2332 to contributors.
  README.md
Labels: documentation

#33 Corrected "Back" option in semchoose.go
  cmd/internal/menu/semchoose.go
Labels: bug-fix, AMWOC, AMWOC-accepted

#30 [WIP] Added sub communities while requesting assesments #18
  README.md
  cmd/internal/menu/semchoose.go
  cmd/internal/menu/subCommunity.go
  cmd/internal/requestclient/requestclient.go
  cmd/internal/requestclient/requestclient_test.go
Labels: enhancement, AMWOC, AMWOC-accepted

#34 Added documentation for unit tests for issue#31
  README.md
  docs/.vitepress/config.js
  docs/CODE_OF_CONDUCT.md
  docs/SECURITY.md
  docs/getting-started.md
  docs/package-lock.json
  docs/testing.md
Labels: documentation, AMWOC, AMWOC-accepted
